#!/bin/sh

case "$1" in
	cv:make)
		\rm -v cv/index.html
		php _src/cv/index.php > cv/index.html
		;;
	cv:dev)
		php -S localhost:8000 _src/cv/index.php
		;;
	cv:upload)
		scp ./cv/* root@sexualise.it:/srv/http/rirekisho.tsuku.ro
		;;
	*)
		echo 'supported commands:'
		echo '- cv:make - builds the cv'
		echo '- cv:dev - local development server for the cv'
		echo '- cv:upload - uploads the cv to tsuku.ro'
esac
