#!/bin/sh

case "$1" in
	make)
		\rm -v cv/index.html
		php _src/cv/index.php > cv/index.html
		;;
	dev:cv)
		php -S localhost:8000 _src/cv/index.php
		;;
	*)
		echo 'supported commands:'
		echo '- make - builds the site'
		echo '- dev:cv - local development server for the cv'
esac
